[technote]
id = "DMTN-298"
series_id = "DMTN"
canonical_url = "https://dmtn-298.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-298"
github_default_branch = "main"
date_created = 2024-09-18T14:12:57Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Gabriele"
name.family = "Mainetti"
internal_id = "mainettig"
orcid = "https://orcid.org/0000-0003-2384-2377"
[[technote.authors.affiliations]]
name = "CNRS"
internal_id = "Lyon-CC-IN2P3"
address = "CC-IN2P3, 21 avenue Pierre de Coubertin, CS70202, F-69627 Villeurbanne cedex, France"
